[general]
import = ["alacritty.toml"]

[terminal]
shell = "fish"

[[hints.enabled]]
binding = { key = "F2" }
regex = "\\S{8,}" # non-whitespace groups
post_processing = true
command = "xdg-open"
hyperlinks = true
mouse = { enabled = true }
