[general]
live_config_reload = true

[font]
normal = { family = "MonaspiceNe Nerd Font Mono", style = "Regular" }
bold = { family = "MonaspiceNe Nerd Font Mono", style = "Bold" }
italic = { family = "MonaspiceXe Nerd Font Mono", style = "Regular" }
bold_italic = { family = "MonaspiceXe Nerd Font Mono", style = "Bold" }

[terminal]
shell = "fish"

[[hints.enabled]]
binding = { key = "F1" }
regex = "[^ ]*\\.[a-zA-Z]+"
post_processing = true
action = "Copy"
mouse = { enabled = true }

