[general]
live_config_reload = true

[font]
normal = { family = "MonaspiceAr Nerd Font Mono", style = "Regular" }
bold = { family = "MonaspiceAr Nerd Font Mono", style = "Bold" }
italic = { family = "MonaspiceRn Nerd Font Mono", style = "Regular" }
bold_italic = { family = "MonaspiceRn Nerd Font Mono", style = "Bold" }

[terminal]
shell = "fish"

[[hints.enabled]]
regex = "[^ ]*\\.[a-zA-Z]+"
post_processing = true
action = "Copy"
mouse = { enabled = true }
binding = { key = "X", mods = "Control" }

